name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install notebook nbconvert

      - name: Execute all notebooks
        run: |
          for nb in $(find . -name "*.ipynb"); do
            echo "Running $nb"
            jupyter nbconvert --to notebook --execute "$nb" --ExecutePreprocessor.timeout=600 --output executed.ipynb
          done